// Parity test: biomechanics.js must produce the SAME fault values as
// swing/biomechanics.py. Ground-truth below was generated by running the Python
// on identical poses (see the README / commit message). Run: node test_biomechanics.mjs
import { analyze } from "./biomechanics.js";

const P = (nose, ls, rs, lh, rh) => ({
  nose: { x: nose[0], y: nose[1] },
  left_shoulder: { x: ls[0], y: ls[1] }, right_shoulder: { x: rs[0], y: rs[1] },
  left_hip: { x: lh[0], y: lh[1] }, right_hip: { x: rh[0], y: rh[1] },
});

const cases = {
  clean: {
    Address: P([100, 50], [80, 100], [120, 100], [85, 200], [115, 200]),
    Top:     P([105, 50], [82, 100], [122, 100], [85, 200], [115, 200]),
    Impact:  P([100, 50], [80, 100], [120, 100], [90, 200], [120, 200]),
  },
  sway_only: {
    Address: P([100, 50], [80, 100], [120, 100], [85, 200], [115, 200]),
    Top:     P([60, 50],  [80, 100], [120, 100], [85, 200], [115, 200]),
    Impact:  P([100, 50], [80, 100], [120, 100], [90, 200], [120, 200]),
  },
  all_three: {
    Address: P([120, 50], [100, 100], [140, 100], [85, 200], [115, 200]),
    Top:     P([160, 50], [100, 100], [140, 100], [85, 200], [115, 200]),
    Impact:  P([120, 50], [40, 100],  [80, 100],  [40, 200], [80, 200]),
  },
};

// From the Python (swing/biomechanics.py) on the identical poses:
const expected = {
  clean: [],
  sway_only: [{ fault: "sway_off_ball", value: -1.0, threshold: 0.4 }],
  all_three: [
    { fault: "sway_off_ball", value: 1.0, threshold: 0.4 },
    { fault: "hip_slide", value: -1.0, threshold: 0.7 },
    { fault: "early_extension", value: 11.3, threshold: 8.0 },
  ],
};

let fail = 0;
for (const [name, poses] of Object.entries(cases)) {
  const got = analyze(poses).map((f) => ({ fault: f.fault, value: f.value, threshold: f.threshold }));
  const exp = expected[name];
  const ok = JSON.stringify(got) === JSON.stringify(exp);
  if (!ok) {
    fail++;
    console.error(`FAIL ${name}\n  expected ${JSON.stringify(exp)}\n  got      ${JSON.stringify(got)}`);
  } else {
    console.log(`ok   ${name}  (${got.length} fault${got.length === 1 ? "" : "s"})`);
  }
}
if (fail) { console.error(`\n${fail} case(s) diverge from the Python.`); process.exit(1); }
console.log("\nAll cases match swing/biomechanics.py — JS fault math verified.");
